backend:
  name: github
  repo: pc-kirchberg/pc4

media_folder: "img"

collections:
  - name: posts
    label: "Posts"
    label_singular: "Post"
    folder: posts
    create: true
    extension: md
    format: frontmatter
    slug: "{{year}}-{{slug}}"
    fields:
      - name: title
        label: Title
        widget: string
        required: true
      - label: Contents
        name: body
        widget: markdown
  - name: people
    label: "Meet The Committee"
    folder: "data/people"
    create: true
    format: json
    slug: "{{slug}}"
    fields:
    - name: name
      label: Name
      widget: string
      required: true
    - name: position
      label: Position
      widget: string
      required: true
    - name: since
      label: Since
      widget: number
      valueType: int
      required: false
    - name: image_url
      label: Photo
      required: false
      widget: image
    - name: bio
      label: Bio
      required: false
      widget: markdown
      buttons: ["bold", "italic", "underscore"]
