backend:
  name: github
  repo: pc-kirchberg/pc4

media_folder: "img"

collections:
  - name: posts
    label: "Posts"
    label_singular: "Post"
    folder: posts
    create: true
    extension: md
    format: frontmatter
    slug: "{{year}}-{{slug}}"
    fields:
      - name: title
        label: Title
        widget: string
        required: true
      - label: Contents
        name: body
        widget: markdown
  - name: pages
    label: "Static Pages"
    folder: "pages"
    create: true
    extension: md
    format: frontmatter
    slug: "{{slug}}"
    fields:
      - name: title
        label: Title
        widget: string
        required: true
      - name: nav
        label: "Show in top-bar navigation?"
        widget: boolean
        default: false
      - name: navtitle
        label: "Page title in navigation"
        required: false
        widget: string
        hint: "Customize the title of this page in the navigation. Leave it blank unless you have a good reason"
      - name: navorder
        label: "Page order in navigation"
        required: false
        widget: number
        valueType: int
        default: 0
        hint: "Change the order of the pages in navigation - pages are displayed in ascending order."
      - name: body
        label: "Content"
        widget: markdown
        
  - name: people
    label: "Meet The Committee"
    folder: "data/people"
    create: true
    format: json
    slug: "{{slug}}"
    fields:
    - name: name
      label: Name
      widget: string
      required: true
    - name: position
      label: Position
      widget: string
      required: true
    - name: since
      label: Since
      widget: number
      valueType: int
      required: false
    - name: image_url
      label: Photo
      required: false
      widget: image
    - name: bio
      label: Bio
      required: false
      widget: markdown
      buttons: ["bold", "italic", "underscore"]
